In [1]:
import numpy as np

In [5]:
#create from list
arr = np.array([1,2,3,4])
print(arr)
print("Shape of aray is : " , arr.shape)
print(type(arr))

arr2 = np.array([1,2,3,4,"Shrey"])
print(arr2, arr.shape)
print(type(arr2))

[1 2 3 4]
Shape of aray is :  (4,)
<class 'numpy.ndarray'>
['1' '2' '3' '4' 'Shrey'] (4,)
<class 'numpy.ndarray'>


In [9]:
#2d array
arr2D = np.array([[1,2,3], [2,5,4], [6,3,9], [5,4,3]])
print(arr2D)
print(f"Dimension of array : {arr2D.shape}")

[[1 2 3]
 [2 5 4]
 [6 3 9]
 [5 4 3]]
Dimension of array : (4, 3)
