In [2]:
import numpy as np

In [3]:
#Creatig arrays using built-in-functions
#arrays with zeros
arr1 = np.zeros((2,3)) #prefill
print(arr1,arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [4]:
#array with ones
arr2 = np.ones((2,3), dtype = "int64")
print(arr2,arr2.shape)

[[1 1 1]
 [1 1 1]] (2, 3)


# Creatiing array with prefilling number 

In [5]:
"""
Synatx : 
arr_name = np.full((n,m), num_to_fill)
n,m : are dimensions
"""
arr3 = np.full((3,4), 100) #prefill with value
print(arr3,arr3.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


# Creating an identity matrix
Identity matrix is a square matrix with diagonals elements "1".

In [6]:
arr4 = np.eye(3)
print(arr4, arr4.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [7]:
arr5 = np.arange(0,12,2)
print(arr5, arr5.shape)

[ 0  2  4  6  8 10] (6,)


In [8]:
#creating evenly spaced array
arr6 = np.linspace(1,100,4)
print(arr6, arr6.shape)

[  1.  34.  67. 100.] (4,)
