In [1]:
import numpy as np

In [2]:
#lets create a 2d array
arr = np.array([[1,2,3],[2,5,2],[5,0,2],[1,2,3]])
print(arr)

[[1 2 3]
 [2 5 2]
 [5 0 2]
 [1 2 3]]


In [3]:
# dimensions of array 
#(arr.shape)
print(arr.shape)

(4, 3)


In [4]:
# size of array (no. of elements)
print(arr.size)

12


In [5]:
#dtype of array
print(arr.dtype)

int64


In [8]:
# total number of dimensions
print(arr.ndim)

2


# Converting existing array by type converting into a new array
eg.: int -> float

In [10]:
arr_float = arr.astype(np.float64)
print(arr_float, arr_float.dtype)

[[1. 2. 3.]
 [2. 5. 2.]
 [5. 0. 2.]
 [1. 2. 3.]] float64
