# Operations on array
1) Reshaping Array :
   - changing the shape (dimensions) of an array without changing its data.
   - eg .:
       1) (3,2) -> (2,3)
       2)   1D -> 2D
       3) 2D -> 1D

In [2]:
import numpy as np

In [11]:
#lets create a 2D array with dimensions (3,2)
arr = np.array([[1,2,3],[3,4,6]])
print(arr)
print(f"Dimensions of numpy array are : {arr.shape}")

[[1 2 3]
 [3 4 6]]
Dimensions of numpy array are : (2, 3)


In [12]:
#Now reshape array 
arr1 = arr.reshape(3,2)
print(arr1)
print(f"Dimensions of numpy array are : {arr1.shape}")

[[1 2]
 [3 3]
 [4 6]]
Dimensions of numpy array are : (3, 2)


Flatten array 
- 2D -> 1D

In [13]:
arr2 = arr1.flatten() 
print(arr2)
print(f"Dimensions of numpy array are : {arr2.shape}")

[1 2 3 3 4 6]
Dimensions of numpy array are : (6,)


# ravel()
- converts to 1D array without generating a copy,just a view
- faster than flatten