# Indexing on arrays (1D and 2D arrays)

In [3]:
import numpy as np

In [4]:
#Lets create a array
arr = np.array([1,2,5,8])
print(arr)

[1 2 5 8]


In [5]:
# Indexing 
#accessing elements from array using index
print(arr[1]) 

2


In [9]:
# Indexing on 2D array
arr2 = np.array([[1,3,2],[3,6,9],[2,1,6]])
print(arr2)

#lets access element 2 from 2D array
print(arr2[2][0])

[[1 3 2]
 [3 6 9]
 [2 1 6]]
2


In [11]:
# Fancy Indexing

#accessing multiple elements at a same time from a 1D array

arr3 = np.array([1,2,5,8,0,3,6])

indx = [0,3,5]
print(arr3[indx])

[1 8 3]


In [16]:
#Boolean Indexing
#pass the condition at place of index
print(" Elements greater than 3 from array are : ",arr3[arr3 > 3]) 
print(" Even Numbers from the array : ",arr3[arr3 % 2 == 0])#even numbers

 Elements greater than 3 from array are :  [5 8 6]
 Even Numbers from the array :  [2 8 0 6]
