# Copy vs View
| Term     | Meaning                                        |
| -------- | ---------------------------------------------- |
| **View** | New array **shares the same data** as original |
| **Copy** | New array with **its own separate data**       |


In [1]:
import numpy as np

In [5]:
#Python lists uses copy
py_list = [1,2,3,4,5,6,7]

new_list = py_list[1 : 4] #new_list is slice (copy) of py_list
print(new_list)

new_list[0] = 200
print(new_list) #chnage at index 0 occurs in new_list
print(py_list) # chanes made in new_list(copy) doesnt show in original py_list



[2, 3, 4]
[200, 3, 4]
[1, 2, 3, 4, 5, 6, 7]


In [8]:
#Numpy arrays uses views
arr = np.array([1,2,3,4,5,6,7])
arr1 = arr[1 : 4]
print(arr1)

arr1[0] = 200
print(arr1)
print(arr)

[2 3 4]
[200   3   4]
[  1 200   3   4   5   6   7]


In [9]:
#if we want copy in numpy array
#and dont want changes made in new arr into orignal array then use .copy() function



In [10]:
arr = np.array([1,2,3,4,5,6,7])
arr1 = arr[1 : 4].copy()
print(arr1)

arr1[0] = 200
print(arr1)
print(arr)

[2 3 4]
[200   3   4]
[1 2 3 4 5 6 7]
