# Multidimensional Arrays
- multidimensional array is simply an array with more than one dimension.
  | Dimension | Name   | Example           |
| --------- | ------ | ----------------- |
| 1D        | Vector | `[1, 2, 3]`       |
| 2D        | Matrix | `[[1,2],[3,4]]`   |
| 3D        | Tensor | Multiple matrices |
| nD        | Tensor | Used in ML & DL   |


2) Creating Multidimensional Arrays in NumPy

In [5]:
import numpy as np

# 1D
a = np.array([1, 2, 3])

# 2D
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3D
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])


3) Understanding Shape, Dimension & Size
   | Property | Meaning              |
| -------- | -------------------- |
| `shape`  | Rows × Columns       |
| `ndim`   | Number of dimensions |
| `size`   | Total elements       |


In [6]:
b.shape     # (2, 3)
b.ndim      # 2
b.size      # 6


6

# Axis :
- Axis tells NumPy in which direction to operate

- Think of axis as direction, not dimension number

| Axis     | Direction    | Meaning     |
| -------- | ------------ | ----------- |
| `axis=0` | ↓ vertical   | Column-wise |
| `axis=1` | → horizontal | Row-wise    |


In [7]:
import numpy as np

In [16]:
#Operations on multidimensional array
arr = np.array([[1,2,3],[4,5,7],[8,4,9]])
print(arr)

print()

sum_of_cols = np.sum(arr, axis = 0)
print(sum_of_cols)

print()

sum_of_rows = np.sum(arr, axis = 1)
print(sum_of_rows)

[[1 2 3]
 [4 5 7]
 [8 4 9]]

[13 11 19]

[ 6 16 21]


# Slicing on multidimensional array

In [17]:
print(arr[0:2 , 1:2])

[[2]
 [5]]
