# 3D Arrays
- (axis 0, axis 1, axis 2)
- = (depth, rows, columns)


In [1]:
import numpy as np

In [5]:
#lets create a 3D array

"""
steps : to create a (2 x 2 x 3) array

arr3D = np.array()
arr3D = np.array([])
arr3D = np.array([ [],[] ])
arr3D = np.array([[[a,c,s],[q,w,e]],[[a,c,s],[q,w,e]]])

"""

arr3D = np.array([[[1,2,3],
                   [4,5,6]],
                  
                  [[4,6,8],
                   [0,3,8]]]) 
print(arr3D)

[[[1 2 3]
  [4 5 6]]

 [[4 6 8]
  [0 3 8]]]


# Indexing on 3D array

In [7]:
# indexing on 3D arrays
#lets search a key = 4 from array 
key = arr3D[0,1,0]
print(key)

#lets search a key = 8 from array 
key = arr3D[1,1,2]
print(key)

4
8


# Slicing on 3D array
- General Slicing Syntax
- array[ depth , rows , columns ]


In [8]:
# slice 1st row from both layers
print(arr3D[:, 0, :])

[[1 2 3]
 [4 6 8]]


In [10]:
# now slice 1st colum
print(arr3D[:,:,0])

[[1 4]
 [4 0]]


In [12]:
print(arr3D[0, 0:1, 0:2])

[[1 2]]


# manupulating data from 3D arrays

In [13]:
arr3D[:,0,:] = 1 #replaing all values of 1st rows with 1
print(arr3D)

[[[1 1 1]
  [4 5 6]]

 [[1 1 1]
  [0 3 8]]]
