# Vectorization
- Vectorization means performing operations on entire arrays at once, without explicit Python loops.
- uses low-level C optimizations inside NumPy.

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3])
arr2 = np.array([3,5,7])

print(arr ** 2)
print(arr + arr2)

[1 4 9]
[ 4  7 10]


# broadcasting 
- Broadcasting allows NumPy to perform operations on arrays of different shapes without copying data.
  

In [7]:
print (arr + 10)

[11 12 13]


NumPy pretends that 10 is [10, 10, 10] (no real copy).

Broadcasting Rules (MOST IMPORTANT)
- Rule 1: Compare shapes from RIGHT to LEFT
(2, 3)
    (3,)

-  Rule 2: Dimensions are compatible if:

They are equal, OR

One of them is 1

- Otherwise → Error